import '@fontsource/public-sans' // Import the Public Sans font
import Footer from './(components)/Footer'
import NavBar from './(components)/NavBar'
import './globals.css' // Import your global styles

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden">
        <NavBar />
        <main>{children}</main>
        <Footer />
      </body>
      <div id="portal" />
    </html>
  )
}
